<?= $this->doctype() ?>
<?php
//$controller = $this->layout()->route ? $this->layout()->route->getParam('controller') : '';
//$action = $this->layout()->route ? $this->layout()->route->getParam('action') : '';
//$parent = $this->layout()->route ? $this->layout()->route->getParam('parent') : '';

//$cookie = $this->layout()->request ? $this->layout()->request->getCookie() : '';

$title = $this->sysConfig('general/info/system_name');
?>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!--<meta name="author" content="Stagem Company" />
    <meta name="description" content="Stagem Cloud - Business System" />
    <meta name="keywords" content="e-commerce" />
    <meta name="application-name" content="Stagem Cloud - Business System" />-->

    <?= $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink() ?>
    <?= $this->headStyle() ?>
</head>
<body class="popup">
<?php // main content ?>

<div id="popup" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<div  class="popup-user-img">
					<div id="myTimer"></div>
					<img src="https://timebase.lt/media/cache/user_small_thumb_retina/uploads/users/3625_70ecc7f6ac82c6ffe622b1cb49814420acdc38b9.jpeg" alt="user">
				</div>
				<div class="guess-buddy">
					<h2>Guess this buddy!</h2>
				</div>
				<hr>
				<div class="answers">
					<div class="answer">
						<div class="answer-item">
							<div class="check">
								<img class="normal" src="img/check.svg" alt="check">
								<img class="success" src="img/check-success.svg" alt="check-success">
								<img class="fail" src="img/check-fail.svg" alt="check-fail">
							</div>
						</div>
						<div class="answer-item">
							<div class="user-name">
								Antanas
								Špečkauskas
							</div>
						</div>
						<div class="answer-item">
							<div class="user-position">
								Partner
							</div>
						</div>
					</div>
					<div class="answer success">
						<div class="answer-item">
							<div class="check">
								<img class="normal" src="img/check.svg" alt="check">
								<img class="success" src="img/check-success.svg" alt="check-success">
								<img class="fail" src="img/check-fail.svg" alt="check-fail">
							</div>
						</div>
						<div class="answer-item">
							<div class="user-name">
								Antanas
								Špečkauskas
							</div>
						</div>
						<div class="answer-item">
							<div class="user-position">
								Partner
							</div>
						</div>
					</div>
					<div class="answer fail">
						<div class="answer-item">
							<div class="check">
								<img class="normal" src="img/check.svg" alt="check">
								<img class="success" src="img/check-success.svg" alt="check-success">
								<img class="fail" src="img/check-fail.svg" alt="check-fail">
							</div>
						</div>
						<div class="answer-item">
							<div class="user-name">
								Antanas
								Špečkauskas
							</div>
						</div>
						<div class="answer-item">
							<div class="user-position">
								Partner
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
			</div>
		</div>

	</div>
</div>

<?php // Include all JS ?>
<?= $this->headScript() ?>
<?= $this->inlineScript() ?>
</body>
</html>
