<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2019 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php $charsetDataset = $this->vars('dataset'); ?>
<?php $dashboardData = $this->vars('dashboard'); ?>

<div id="statistic_popup" class="modal fade" role="dialog">
	<form id="picker-form">
		<input type="hidden" id="user" name="user" value="" />
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<img src="/img/TF_logo_s.png"  class="logo" alt="logo">
					<button type="button" class="close" data-dismiss="modal"><img src="/img/Close.svg" alt="close"></button>
				</div>
				<div class="modal-body">

				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</form>
</div>
