<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2019 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>

<!--<script src="../../../dist/Chart.min.js"></script>-->
<!--<script src="../../utils.js"></script>-->
<!--<style>-->
<!--	canvas{-->
<!--		-moz-user-select: none;-->
<!--		-webkit-user-select: none;-->
<!--		-ms-user-select: none;-->
<!--	}-->
<!--</style>-->

<div>
	HI!!!
	<?php
		echo "hey!";
	?>
<!--	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>-->
<!--	<div style="width:75%;">-->
<!--		<canvas id="canvas"></canvas>-->
<!--	</div>-->



</div>

<!---->
<!--<script>-->
<!--  var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];-->
<!--  var config = {-->
<!--    type: 'line',-->
<!--    data: {-->
<!--      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],-->
<!--      datasets: [{-->
<!--        label: 'My First dataset',-->
<!--        backgroundColor: window.chartColors.red,-->
<!--        borderColor: window.chartColors.red,-->
<!--        data: [-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor()-->
<!--        ],-->
<!--        fill: false,-->
<!--      }, {-->
<!--        label: 'My Second dataset',-->
<!--        fill: false,-->
<!--        backgroundColor: window.chartColors.blue,-->
<!--        borderColor: window.chartColors.blue,-->
<!--        data: [-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor(),-->
<!--          randomScalingFactor()-->
<!--        ],-->
<!--      }]-->
<!--    },-->
<!--    options: {-->
<!--      responsive: true,-->
<!--      title: {-->
<!--        display: true,-->
<!--        text: 'Chart.js Line Chart'-->
<!--      },-->
<!--      tooltips: {-->
<!--        mode: 'index',-->
<!--        intersect: false,-->
<!--      },-->
<!--      hover: {-->
<!--        mode: 'nearest',-->
<!--        intersect: true-->
<!--      },-->
<!--      scales: {-->
<!--        xAxes: [{-->
<!--          display: true,-->
<!--          scaleLabel: {-->
<!--            display: true,-->
<!--            labelString: 'Month'-->
<!--          }-->
<!--        }],-->
<!--        yAxes: [{-->
<!--          display: true,-->
<!--          scaleLabel: {-->
<!--            display: true,-->
<!--            labelString: 'Value'-->
<!--          }-->
<!--        }]-->
<!--      }-->
<!--    }-->
<!--  };-->
<!--  window.onload = function() {-->
<!--    var ctx = document.getElementById('canvas').getContext('2d');-->
<!--    window.myLine = new Chart(ctx, config);-->
<!--  };-->
<!--  document.getElementById('randomizeData').addEventListener('click', function() {-->
<!--    config.data.datasets.forEach(function(dataset) {-->
<!--      dataset.data = dataset.data.map(function() {-->
<!--        return randomScalingFactor();-->
<!--      });-->
<!--    });-->
<!--    window.myLine.update();-->
<!--  });-->
<!--  var colorNames = Object.keys(window.chartColors);-->
<!--  document.getElementById('addDataset').addEventListener('click', function() {-->
<!--    var colorName = colorNames[config.data.datasets.length % colorNames.length];-->
<!--    var newColor = window.chartColors[colorName];-->
<!--    var newDataset = {-->
<!--      label: 'Dataset ' + config.data.datasets.length,-->
<!--      backgroundColor: newColor,-->
<!--      borderColor: newColor,-->
<!--      data: [],-->
<!--      fill: false-->
<!--    };-->
<!--    for (var index = 0; index < config.data.labels.length; ++index) {-->
<!--      newDataset.data.push(randomScalingFactor());-->
<!--    }-->
<!--    config.data.datasets.push(newDataset);-->
<!--    window.myLine.update();-->
<!--  });-->
<!--  document.getElementById('addData').addEventListener('click', function() {-->
<!--    if (config.data.datasets.length > 0) {-->
<!--      var month = MONTHS[config.data.labels.length % MONTHS.length];-->
<!--      config.data.labels.push(month);-->
<!--      config.data.datasets.forEach(function(dataset) {-->
<!--        dataset.data.push(randomScalingFactor());-->
<!--      });-->
<!--      window.myLine.update();-->
<!--    }-->
<!--  });-->
<!--  document.getElementById('removeDataset').addEventListener('click', function() {-->
<!--    config.data.datasets.splice(0, 1);-->
<!--    window.myLine.update();-->
<!--  });-->
<!--  document.getElementById('removeData').addEventListener('click', function() {-->
<!--    config.data.labels.splice(-1, 1); // remove the label first-->
<!--    config.data.datasets.forEach(function(dataset) {-->
<!--      dataset.data.pop();-->
<!--    });-->
<!--    window.myLine.update();-->
<!--  });-->
<!--</script>-->