<form class="form-login" method="post" name="login" id="login">
	<div class="col-sm-12">
		<div class="form-login-block">
			<h1 class="formH2 padding50">Log in to Timebase</h1>
			<div class="fromGroup">
				<input type="text" name="email" required value="" class="input" placeholder="Enter your email">
				<input type="password" name="password" value="" class="input" placeholder="Enter your password">
			</div>
			<div class="formGroup2 buttons-group">
				<input name="save" type="submit" value="log in" class="sing_up_for_free text-center loginbtn">
				<a href="/remind-password" class="forgotPasword">Forgot your password?</a>
			</div>
		</div>
	</div>
	<div class="col-sm-12 col-xs-12">
		<a href="/login-with-google">
			<div class="sinUpForm2 text-center">
				<div class="sinUpForm2Btn">Log in with Google</div>
			</div>
		</a>
	</div>
</form>