<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2019 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_Picker
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php /** @var \Popov\ZfcUser\Model\User[] $users */ ?>
<?php $users = $this->picker()->getUsers(); ?>
<?php $guessed = $users[rand(0, count($users) - 1)]; ?>
<div id="popup" class="modal fade" role="dialog">
	<form id="picker-form">
		<input type="text" id="user" name="user" value="<?= $guessed->getId() ?>" />

		<div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div  class="popup-user-img">
                    <div id="myTimer"></div>
                    <img src="<?= $guessed->getPhoto() ?>" alt="user">
                </div>
                <div class="guess-buddy">
                    <h2>Guess this buddy!</h2>
                </div>
                <hr>
                <div class="answers">
                    <?php foreach ($users as $user) : ?>
		                <div class="answer" data-user="<?= $user->getId() ?>">
		                    <div class="answer-item">
	                            <div class="check">
	                                <img class="normal" src="/img/check.svg" alt="check">
	                                <img class="success" src="/img/check-success.svg" alt="check-success">
	                                <img class="fail" src="/img/check-fail.svg" alt="check-fail">
	                            </div>
	                        </div>

	                        <div class="answer-item">
	                            <div class="user-name">
	                                <?= $user->getFullName() ?>
	                            </div>
	                        </div>
	                        <div class="answer-item">
	                            <div class="user-position">
                                    <?= $this->picker()->extra($user, 'occupation') ?>
	                            </div>
	                        </div>
	                    </div>
	                <?php endforeach; ?>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
	</form>
</div>
