<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2019 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Stagem
 * @package Stagem_Picker
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php /** @var \Popov\ZfcUser\Model\User[] $users */ ?>
<?php $users = $this->picker()->getUsers(); ?>
<?php $guessed = $this->picker()->getGuessedUser(); ?>

<div id="popup" class="modal fade" role="dialog">
	<form id="picker-form">
		<input type="hidden" id="user" name="user" value="<?= $guessed->getId() ?>" />

		<div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div  class="popup-user-img">
                    <div id="myTimer"></div>
                    <img src="<?= $guessed->getPhoto() ?>" alt="user">
                </div>
                <div class="guess-buddy">
                    <h2 class="buddy">Guess this buddy!</h2>
	                <h2 class="result">
		                <?= $guessed->getFullName(); ?>
	                </h2>
                </div>
                <div class="progresses">
	                <div class="success"></div>
	                <div class="fail"></div>
                </div>
                <div class="answers">
                    <?php foreach ($users as $user) : ?>
		                <div class="answer" data-user="<?= $user->getId() ?>">
		                    <div class="answer-item">
	                            <div class="check">
	                                <img class="normal" src="/img/check.svg" alt="check">
	                                <img class="success" src="/img/check-success.svg" alt="check-success">
	                                <img class="fail" src="/img/check-fail.svg" alt="check-fail">
	                            </div>
	                        </div>
	                        <div class="answer-item">
	                            <div class="user-name">
	                                <?= $user->getFullName() ?>
	                            </div>
	                        </div>
	                        <div class="answer-item">
	                            <div class="user-position">
                                    <?= $this->picker()->extra($user, 'occupation') ?>
		                        </div>
	                        </div>
			                <div class="answer-item">
				                <div class="user-group-title">
                                    <?= $this->picker()->extra($user, 'project_group_title') ?>
				                </div>
			                </div>
	                    </div>
	                <?php endforeach; ?>
                </div>
	            <div class="user-result">
		          <div class="user-info">
			            <div class="result-user-name">
							<span><?= $guessed->getFullName() ?></span>
			            </div>
                       <?php if($this->picker()->extra($guessed, 'occupation')): ?>
			            <div class="result-user">
				            <span class="title-info">Occupation: </span>
				            <span class="info"><?= $this->picker()->extra($guessed, 'occupation') ?></span>
			            </div>
                      <?php endif;?>
			          <?php if($this->picker()->extra($guessed, 'project_group_title')): ?>
			            <div class="result-user">
				            <span class="title-info">Branch: </span>
				            <span class="info"> <?= $this->picker()->extra($guessed, 'project_group_title') ?></span>
			            </div>
                      <?php endif;?>
			          <?php if($guessed->getEmail()): ?>
			            <div class="result-user">
				            <span class="title-info"><img src="img/email.svg" alt="email"></span>
				            <span class="info"> <?= $guessed->getEmail() ?></span>
			            </div>
                      <?php endif;?>
			          <?php if($guessed->getPhone()): ?>
			            <div class="result-user">
				            <span class="title-info"><img src="img/phone.svg" alt="phone"></span>
				            <span class="info"> <?= $guessed->getPhone() ?></span>
			            </div>
                      <?php endif;?>
			          <?php if($this->picker()->extra($guessed, 'skype')): ?>
			            <div class="result-user">
				            <span class="title-info"><img src="img/Skype.svg" alt="skype"></span>
				            <span class="info"> <?= $this->picker()->extra($guessed, 'skype') ?></span>
		                </div>
			          <?php endif;?>
		           </div>
	            </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
	</form>
</div>
