<?php
/**
 * The MIT License (MIT)
 * Copyright (c) 2019 Serhii Popov
 * This source file is subject to The MIT License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/MIT
 *
 * @category Popov
 * @package Popov_<package>
 * @author Serhii Popov <popow.serhii@gmail.com>
 * @license https://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<?php /** @var \Popov\ZfcUser\Model\User[] $users */ ?>
<?php $users = $this->vars('users'); ?>
<?php $guessed = $users[rand(0, count($users) - 1)]; ?>
<div>
	<form id="picker-form">
		<?php //@todo Remember ID of searchable user in session ?>
		<input type="text" id="user" name="user" value="<?= $guessed->getId() ?>" />

		<div>Here must be user photo</div>

		<?php foreach ($users as $user) : ?>
			<div><a href="#" class="picked" data-id="<?= $user->getId() ?>"><?= $user->getFullName() ?></a></div>
		<?php endforeach; ?>
	</form>
</div>
